package org.fptn.vpn.enums;

public enum SniSpoofingMode {
    SNI,
    /* Yandex Browser */
    SNI_REALITY_YANDEX_26_4,
    SNI_REALITY_YANDEX_26_3,
    SNI_REALITY_YANDEX_25,
    SNI_REALITY_YANDEX_24,
    /* Firefox */
    SNI_REALITY_FIREFOX_151,
    SNI_REALITY_FIREFOX_150,
    SNI_REALITY_FIREFOX_149,
    /* Safari */
    SNI_REALITY_SAFARI_26_5,
    SNI_REALITY_SAFARI_26_4,
    /* Chrome */
    SNI_REALITY_CHROME_149,
    SNI_REALITY_CHROME_148,
    SNI_REALITY_CHROME_147,
    SNI_REALITY_CHROME_146,
    SNI_REALITY_CHROME_145,
}
